name: Fetch updates

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  pulls:
    runs-on: ubuntu-latest
    if: github.repository != 'kyori19/web-updates-checker'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: |
          echo "REPOSITORY_OWNER=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')" >> $GITHUB_ENV

      - run: npm ci

      - run: npm run process-pull-requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
