name: Cleanup pull requests

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.repository != 'kyori19/web-updates-checker'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git push origin :${{ github.event.pull_request.head.ref }}
